# Qnote BACKEND - one-click deploy to Render
# README: https://render.com/docs/yaml-spec
services:
  - type: web
    name: qnote-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: CORS_ORIGINS
        value: "*"
        sync: false
      - key: ADMIN_USERNAME
        value: admin@notes.local
        sync: false
      - key: ADMIN_PASSWORD
        value: admin123
        sync: false
      - key: FIREBASE_API_KEY
        value: AIzaSyBw1vhpCHelRkv8BMnCcemQ-50xZyMCdc0
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        value: note-site-je.firebaseapp.com
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: note-site-je
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        value: note-site-je.firebasestorage.app
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: "1011717430011"
        sync: false
      - key: FIREBASE_APP_ID
        value: 1:1011717430011:web:ec41c01ffc09014d422e5e
        sync: false
